# Generated by Django 2.2.7 on 2019-11-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='Dept_id',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AlterField(
            model_name='authority',
            name='Dept_name',
            field=models.CharField(default='IncomeTax', max_length=50),
        ),
        migrations.AlterField(
            model_name='authority',
            name='Email_id',
            field=models.EmailField(default='shadow@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='Company_id',
            field=models.CharField(default='123', max_length=50),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='Company_name',
            field=models.CharField(default='BBC', max_length=50),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='Email_id',
            field=models.EmailField(default='shadow@gmail.com', max_length=254, null=True),
        ),
    ]
